version: '3.8'

services:
  appointments:
    image: abdullah144/dappointments-app:cb760cd1f85d4f0273a8a2976c3159fce2bebcb3
    ports:
      - "7070:7070"
    networks:
      - app_network

  doctors:
    image: ${{ secrets.DOCKER_USERNAME }}/doctors-app:doctors
    ports:
      - "9090:9090"
    networks:
      - app_network

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend-app:frontend
    ports:
      - "3000:3000" 
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:3.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
