version: '3.8'

services:
  appointments:
    image: abdullah144/appointments-app:e12b80fca0bfb6ee665196d7daa49914fc4f747a
    ports:
      - "7070:7070"
    networks:
      - app_network

  doctors:
    image: abdullah144/doctors-app:e12b80fca0bfb6ee665196d7daa49914fc4f747a
    ports:
      - "9090:9090"
    networks:
      - app_network

  frontend:
    image: abdullah144/frontend-app:f435ff6807996ba08904e2cadb52dfcba0bddfc3
    ports:
      - "3000:3000" 
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:3.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
