version: '3.8'

services:
  appointments:
    image: abdullah144/appointments-app:9b82458c0f5c8e2f18fcd4d2ce48dfd2c4a74e93
    ports:
      - "7070:7070"
    environment:
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - app_network

  doctors:
    image: abdullah144/doctors-app:05279965bb9fd69374fddb31267f77a22c301a76
    ports:
      - "9090:9090"
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090 
    networks:
      - app_network

  frontend:
    image: abdullah144/frontend-app:fc4f678afba449fb787282c19b9fcdd7efdf43f7
    ports:
      - "3000:3000" 
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    depends_on:
      - doctors
      - appointments
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge