version: '3.8'

services:
  appointments:
image: abdullah144/appointments-app:0fc90ccd9db309b9cadc7608299cf433717a63f1s-app:fb825c3cad2002f4749aeae194da4b837cbb6058s-app:3ea7b26bf42df2f625108ce63ad8c7cc36cc4f0fs-app:b5aa8c3ae749288ae3f4a88a2be55474753dee8fs-app:1c22f43e9cf6571dad426c6b9f7f305bd00b1830s-app:2100afed72fc821430fd592263aa8584d50b052cs-app:c9337bb5b37578610b5b365599e55290ef0e5b15
    ports:
      - "7070:7070"
    networks:
      - app_network

  doctors:
    image: ${{ secrets.DOCKER_USERNAME }}/doctors-app:doctors
    ports:
      - "9090:9090"
    networks:
      - app_network

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend-app:frontend
    ports:
      - "3000:3000" 
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:3.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
