version: '3.8'

services:
  appointments:
    image: abdullah144/appointments-app:d14054c461072fa614d2a04bea18836a58dd8bb5
    ports:
      - "7070:7070"
    networks:
      - app_network

  doctors:
    image: abdullah144/doctors-app:d14054c461072fa614d2a04bea18836a58dd8bb5
    ports:
      - "9090:9090"
    networks:
      - app_network

  frontend:
    image: abdullah144/frontend-app:frontend
    ports:
      - "3000:3000" 
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:3.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
