version: '3.8'

services:
  appointments:
    image: abdullah144/appointments-app:371675832226c41920eae4e7cbbff239c27cc135
    ports:
      - "7070:7070"
    networks:
      - app_network

  doctors:
    image: abdullah144/doctors-app:89e4644f42b267a60812bd047f2c212e5d5bcdbf
    ports:
      - "9090:9090"
    networks:
      - app_network

  frontend:
    image: abdullah144/frontend-app:d993cad207e6f99de7584d1fedd8feffd46a9d8f
    ports:
      - "3000:3000" 
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:3.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
