version: '3.8'

services:
  appointments:
    image: abdullah144/appointments-app:ea020e7b5b0a2af1005d45f254e1a5a5d9600650
    ports:
      - "7070:7070"
    networks:
      - app_network

  doctors:
    image: abdullah144/doctors-app:bdb451b341b1d195bd278073fa13817e95cc6fe1
    ports:
      - "9090:9090"
    networks:
      - app_network

  frontend:
    image: abdullah144/frontend-app:ea020e7b5b0a2af1005d45f254e1a5a5d9600650
    ports:
      - "3000:3000" 
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:3.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
