version: '3.8'

services:
  appointments:
    image: abdullah144/appointments-app:4f8a1c600fdb83e590040f1a60bb430bad394a8e
    ports:
      - "7070:7070"
    environment:
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - app_network

  doctors:
    image: abdullah144/doctors-app:c57fdadac432ef829c2fa26d10d5c4fd0c5f1130
    ports:
      - "9090:9090"
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090 
    networks:
      - app_network

  frontend:
    image: abdullah144/frontend-app:b9019520c815dba77ac4b5546a9d4c57e6077489
    ports:
      - "3000:3000" 
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    depends_on:
      - doctors
      - appointments
    networks:
      - app_network
  #you said to assume it has db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - app_network
networks:
  app_network:
    driver: bridge