# Bonus secret environment variables NAME and PASSWORD
apiVersion: v1
kind: Secret
metadata:
  name: appointment
type: Opaque
data:
  NAME: YWJkdWxsYWg= # base64_encoded_name
  PASSWORD: Y2hhbGxhaW4= # base64_encoded_password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
  labels:
    app: appointments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: abdullah144/appointments-app:9b82458c0f5c8e2f18fcd4d2ce48dfd2c4a74e93
          ports:
            - containerPort: 7070
          env: 
            - name: APPOINTMENTS_SERVICE_URL
              value: "appointments:7070"
          envFrom:
            - secretRef:
                name: appointment
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            tcpSocket:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 7070
            initialDelaySeconds: 20
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: appointments
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
