name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'

jobs:
  build-and-deploy-doctors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Check for changes in Doctors directory
        id: check_doctors_changes
        run: |
            CHANGED_DOCTORS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^doctors/')
            if [ -n "$CHANGED_DOCTORS" ]; then
                echo "::set-output name=changed_doctors::true"
            else
                echo "::set-output name=changed_doctors::false"
            fi

      - name: Build and push Doctors microservice
        if: steps.check_doctors_changes.outputs.changed_doctors == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./doctors
          file: ./doctors/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/doctors-app:${{ github.sha }}

      - name: Update docker-compose file
        if: steps.check_doctors_changes.outputs.changed_doctors == 'true'
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/doctors-app:${{ github.sha }}|" docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update docker-compose file with new image tag"
          git push

  build-and-deploy-appointments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Check for changes in Appointments directory
        id: check_appointments_changes
        run: |
            CHANGED_APPOINTMENTS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^appointments/')
            if [ -n "$CHANGED_APPOINTMENTS" ]; then
              echo "::set-output name=changed_appointments::true"
            else
              echo "::set-output name=changed_appointments::false"
            fi

      - name: Build and push Appointments microservice
        if: steps.check_appointments_changes.outputs.changed_appointments == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./appointments
          file: ./appointments/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/appointments-app:${{ github.sha }}

      - name: Update docker-compose file
        if: steps.check_appointments_changes.outputs.changed_appointments == 'true'
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/appointments-app:${{ github.sha }}|" docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update docker-compose file with new image tag"
          git push

  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Check for changes in Frontend directory
        id: check_frontend_changes
        run: |
            CHANGED_FRONTEND=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/')
            if [ -n "$CHANGED_FRONTEND" ]; then
              echo "::set-output name=changed_frontend::true"
            else
              echo "::set-output name=changed_frontend::false"
            fi

      - name: Build and push Frontend microservice
        if: steps.check_frontend_changes.outputs.changed_frontend == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ github.sha }}

      - name: Update docker-compose file
        if: steps.check_frontend_changes.outputs.changed_frontend == 'true'
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ github.sha }}|" docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update docker-compose file with new image tag"
          git push
