name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
        - 'doctors/**'
        - 'appointments/**'
        - 'frontend/**'

jobs:
  build-and-deploy-doctors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Doctors microservice
        uses: docker/build-push-action@v2
        with:
          context: ./doctors
          file: ./doctors/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/doctors-app:${{ github.sha }}

      - name: Update docker-compose file
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/doctors-app:${{ github.sha }}|" Docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update docker-compose file with new image tag"
          git push

  build-and-deploy-appointments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Appointments microservice
        uses: docker/build-push-action@v2
        with:
          context: ./appointments
          file: ./appointments/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/appointments-app:${{ github.sha }}

      - name: Update docker-compose file
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/appointments-app:${{ github.sha }}|" Docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update docker-compose file with new image tag"
          git push

  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Frontend microservice
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ github.sha }}

      - name: Update docker-compose file
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ github.sha }}|" Docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update docker-compose file with new image tag"
          git push
