name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'

jobs:
  build-and-deploy-doctors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get list of modified files
        id: get-modified-files
        run: |
                git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified-files.txt
                if grep -q 'doctors/' modified-files.txt; then
                  echo "::set-output name=doctors_changed::true"
                fi
        # These both steps will only run if changes made in doctors folder
      - name: Build and push Doctors microservice
        if: steps.get-modified-files.outputs.doctors_changed == 'true'
        uses: docker/build-push-action@v2
        with:
              context: ./doctors
              push : true
              tags: |
                  ${{ secrets.DOCKER_USERNAME }}/doctors-app:${{ github.sha }}

      - name: Update docker-compose file
        if: steps.get-modified-files.outputs.doctors_changed == 'true'
        run: |
          git config --global user.email "muhammad.abdullah2gr8@gmail.com"
          git config --global user.name "abdullah1464"
          sed -i -E '/^\s+doctors:/,/^\s*$/ s|^(\s+image:\s+abdullah144/doctors-app:).+|\1'"${{ github.sha }}"'|' Docker-compose.yml
          cat Docker-compose.yml
          git add Docker-compose.yml
          git commit -m "Update doctors microservice image tag to ${GITHUB_SHA}"
          git pull origin main --no-rebase
          git push

  build-and-deploy-appointments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get list of modified files
        id: get-modified-files
        run: |
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified-files.txt
            if grep -q 'appointments/' modified-files.txt; then
              echo "::set-output name=appointments_changed::true"
            fi
        # These both steps will only run if changes made in appointments folder
      - name: Build and push Appointments microservice
        if: steps.get-modified-files.outputs.appointments_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./appointments
          push : true
          tags: |
              ${{ secrets.DOCKER_USERNAME }}/appointments-app:${{ github.sha }}

      - name: Update docker-compose file
        if: steps.get-modified-files.outputs.appointments_changed == 'true'
        run: |
            git config --global user.email "muhammad.abdullah2gr8@gmail.com"
            git config --global user.name "abdullah1464"
            sed -i -E '/^\s+appointments:/,/^\s*$/ s|^(\s+image:\s+abdullah144/appointments-app:).+|\1'"${{ github.sha }}"'|' Docker-compose.yml
            cat Docker-compose.yml
            git add Docker-compose.yml
            git commit -m "Update Appointments microservice image tag to ${GITHUB_SHA}"
            git pull origin main --no-rebase
            git push

  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get list of modified files
        id: get-modified-files
        run: |
              git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > modified-files.txt
              if grep -q 'frontend/' modified-files.txt; then
                echo "::set-output name=frontend_changed::true"
              fi
      # These both steps will only run if changes made in frontend folder
      - name: Build and push Frontend microservice
        if: steps.get-modified-files.outputs.frontend_changed == 'true'
        uses: docker/build-push-action@v2
        with:
            context: ./frontend
            push : true
            tags: |
                ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ github.sha }}
  

      - name: Update docker-compose file
        if: steps.get-modified-files.outputs.frontend_changed == 'true'
        run: |
            git config --global user.email "muhammad.abdullah2gr8@gmail.com"
            git config --global user.name "abdullah1464"
            sed -i -E '/^\s+frontend:/,/^\s*$/ s|^(\s+image:\s+abdullah144/frontend-app:).+|\1'"${{ github.sha }}"'|' Docker-compose.yml
            cat Docker-compose.yml
            git add Docker-compose.yml
            git commit -m "Update frontend microservice image tag to ${GITHUB_SHA}"
            git pull origin main --no-rebase
            git push
