name: CI/CD Pipeline

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Doctors microservice
      uses: docker/build-push-action@v2
      with:
        context: ./doctors
        file: ./doctors/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/doctors-app:${{ github.sha }}

    - name: Build and push Appointments microservice
      uses: docker/build-push-action@v2
      with:
       context: ./appointments
       push: true
       tags: |
         ${{ secrets.DOCKER_USERNAME }}/appointments-app:${{ github.sha }}

    - name: Build and push Frontend microservice
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: |
         ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ github.sha }}