name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'doctors/**'
  pull_request:
    branches:
      - main
    paths:
      - 'doctors/**'

jobs:
    build-and-deploy-doctors:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
    
          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
          - name: Build and push Doctors microservice
            uses: docker/build-push-action@v3
            with:
                  context: ./doctors
                  push : true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/doctors-app:${{ github.sha }}
    
          - name: Update docker-compose file
            run: |
              git config --global user.email "muhammad.abdullah2gr8@gmail.com"
              git config --global user.name "abdullah1464"
              sed -i -E '/^\s+doctors:/,/^\s*$/ s|^(\s+image:\s+abdullah144/doctors-app:).+|\1'"${{ github.sha }}"'|' Docker-compose.yml
              cat Docker-compose.yml
              git add Docker-compose.yml
              git commit -m "Update doctors microservice image tag to ${GITHUB_SHA}"
              git pull origin main --no-rebase
              git push